spring:
  profiles:
    active: local
  application:
    name: streaming-app

azure:
  cosmos:
    uri: <COSMOS_DB_URI>
    key: <COSMOS_DB_KEY>
    database: rcar
    populate-query-metrics: true
    connection-mode: gateway